### ISSUE TITLE
[Docs] Write good documentation

### ISSUE THREAD

**Issue by axmad386** [kodepandai/lunox#13]
Need good documentation. Next we must add github page for full documentation.

**Comment by axmad386** [comment]
Sudah lumayan komplit ini framework nya.
Ada yang mau nyoba? Skalian dibuatkan dokumentasi yang bagus, hehe
@sangvictim @hilmiardani @agung3wi @lakuapik @malikkubs @tamacroft
Cara installnya sementara pake degit
```bash
npx degit kodepintar/lunox lunox-app
```
jangan lupa copy .env.example ke .env

**Comment by lakuapik** [comment]
mungkin harus sampean @axmad386 init dulu mas dokumentasinya, karena yang tahu seluk beluk proyeknya. dan biar kita juga bisa coba dengan panduan getting stared. nah stelah itu mungkin kalau ada kurang-kurang baru kita bisa bantu.

**Comment by axmad386** [comment]
Yoi mas, lg tk cicil2. Cukup banyak yang harus didokumentasikan :v

**Comment by axmad386** [comment]
@lakuapik iya mas, dokumentasine sedang proses. Masih banyak yang belum tertulis :laughing: 
Bahasa inggrisku acak2an lagi :rofl:

**Comment by axmad386** [comment]
> mungkin harus sampean @axmad386 init dulu mas dokumentasinya, karena yang tahu seluk beluk proyeknya. dan biar kita juga bisa coba dengan panduan getting stared. nah stelah itu mungkin kalau ada kurang-kurang baru kita bisa bantu.

Bikin dokumentasi yang pakai github page itu pakai apa mas?

**Comment by axmad386** [comment]
Lunox Documentation moved to separate repo. Please look at this [lunox-website](https://github.com/kodepintar/lunox-webiste).
And the website live at https://kodepintar.github.io/lunox/
