### ISSUE TITLE
[Feature Request] Prisma Support

### ISSUE THREAD

**Issue by damarsimple** [kodepandai/lunox#20]
I believe this frameworks main goals to be Laravel of NodeJS right?

currently i don't see any  Eloquent Query Builder  like ability on this framework.

This is why i propose Prisma support as replacement for the query builder.
although im not sure what is your current plant for building the query builder.
i believe this is gonna be beneficial to the project.

Pros : 

- Easy Data Modelling
- Easy Pagination, Sorting, Filtering 
- Support for wide array of database SQLite , MySQL, PostgreSQL, MongoDB (Preview), CockroachDB (Preview) 
- Fast Query Engine written in Rust
- Type Safety

Cons : 
- Lack of polymorphism support
- Different way to model data and relations compared to Laravel
- Dependent on third party ORM library
- Telemetry (can opt-out)

i might be wrong, but please do correct me.

**Comment by axmad386** [comment]
Actually the skeleton app already using objection.js for ORM.
for example is User model in `app/Model` folder. 
I never use prisma before, but if it better than objection.js, maybe we can refactor the Base Model to use prisma instead.

**Comment by axmad386** [comment]
For additional info, lunox migration is using knex. You can check by run artisan
```
pnpm artisan make:migration create_some_table
```
So if we change to prisma, we should change current migration command too

**Comment by damarsimple** [comment]
i guess i just gonna lookup how the current ORM works before thinking of the possibilty of adding prisma to this project.

Thank you for replying
