### ISSUE TITLE
Bug Router Parameter in windows

### ISSUE THREAD

**Issue by malikkubs** [kodepandai/lunox#30]
kalo memakai router seperti loacalhost:8000/:slug di linux, css styling tidak dapat berjalan, dan di windows menampilkan halaman 404

sedangkan memakai router seperti localhost:8000/test/slug di linux dapat menampiklan halaman secara sempurna, sedangkan di windows menampilkan 404 bukan 303 ye.

**Comment by axmad386** [comment]
confirmed, sudah saya tes di windows memang terjadi bug. Thanks mas @malikkubs.
Untuk tracking saya jadikan satu di issue ini ya https://github.com/kodepandai/lunox-framework/issues/16
Btw untuk route seperti ini misal
```js
Route.get('/:slug', ...)
```
Tidak disarankan, karena semua file yang di public menjadi tidak terbaca. Misal `localhost:8000/app.css` akan diarahkan ke route `/:slug`.

**Comment by axmad386** [comment]
fixed, see https://github.com/kodepandai/lunox-framework/issues/16
